### ISSUE TITLE
Generating Items in Minecraft Error

### ISSUE THREAD

**Issue by compX44** [Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.20.X#2]
Hello Kaupenjoe. I was following along with your video for the custom items and I ran into an issue. I followed your instruction, but when I went to generate the item in Minecraft, a checkerboard pattern showed up where the ruby and raw ruby should be. I compared my code to yours, but I couldn't see where I went wrong. May you please advise?

Here is the link to my project: https://github.com/compX44/MC_Fabric_1.20_Custom-Items-Tutorial-Mod.git

**Comment by compX44** [comment]
Never mind. I restarted the project and it works now. Thank you anyway. I look forward to learning more from you.

**Comment by schnow265** [comment]
There is a big button with "close Issue" down there. Press it.

**Comment by compX44** [comment]
I see it. Thank you @schnow265.
